name: HTML Validation

on:
  push:
    branches:
      - '*'
      - '!Labo2'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Checks HTML5
      uses: Cyb3r-Jak3/html5validator-action@<latest version>
      with:
        root: /
        
