name: HTML Validation

on:
  push:
    branches:
      - '*'
      - '!Labo2'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: ​actions/checkout@v4
    - name: ​✔HTML5 Validator 
      uses: ​Cyb3r-Jak3/html5validator-action@v7.2.0
      with: 
        root​: ​./ 
