name: HTML Validation

on:
  push:
    branches:
      - '*'
      - '!Labo2'

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup cache
        uses: actions/cache@v2
        with:
          path: |
            /.github/workflows/cache/validator-20.8.0.jar
          key: ${{ runner.os }}-validator-20.8.0
        id: cache

      - name: Install required packages
        run: |
          sudo apt-get update
          sudo apt-get install -y default-jre
          if [[ -z "${{ steps.cache.outputs.cache-hit }}" ]]; then
            wget https://validator.github.io/validator/validator-20.8.0.jar -O /.github/workflows/cache/validator-20.8.0.jar
          fi
        shell: bash

      - name: Validate HTML
        run: |
          java -Xss256k -cp /.github/workflows/cache/validator-20.8.0.jar nu.validator.servlet.Main \
          https://your-website.com
        continue-on-error: true
        shell: bash

      - name: Upload validation results
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: validation-results
          path: ./results/
