name: HTML+CSS Validation

on:
  push:
    branches:
      - '*'
      - '!Labo2'
      - '!labo_3'
      - '!labo_8'

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v4
    - name: HTML+CSS validation
      uses: Cyb3r-Jak3/html5validator-action@v7.2.0
      with:
        root: ./
        extra: --show-warnings
        blacklist: 'Labo 3''Labo 7''Labo 8''automatic_index_generating'
        css: true
        log_level: DEBUG
    - name: debug
      run: |
        echo "test1"
        echo "$INPUT_BLACKLIST"
        echo "test2"
