name: HTML+CSS Validation

on:
  push:
    branches:
      - '*'
      - '!Labo2'
      - '!labo_3'
      - '!labo_7'
      - '!labo_8'
      - '!labo_9'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: HTML+CSS validation
      uses: Cyb3r-Jak3/html5validator-action@v7.2.0
      with:
        root: ./
        blacklist: automatic_index_generating
        css: true
        extra: "--show-warnings --ignore-re /\\.\\/Labo%203\\/|\\.\\/Labo%207\\/|\\.\\/Labo%208\\/|\\.\\/Labo%209\\//"
